### PR TITLE
add jsx highlighting

### PR DESCRIPTION
**Pull request by schmittyjd**
After using react for a while at work I wanted to do some more specific highlighting for jsx tags.

Before:

After:

I think the blue color for opening and magenta color for closing is a nice addition. If not tags could also just be blue. Let me know what you think!

### CODE REVIEW

**Comment by benogle** [comment]
I'd rather have the begin and closing tags the same color. Maybe blue `<` and magenta tag names? Or really, the tag names should use [syntax-color-tag](https://github.com/atom/solarized-dark-syntax/blob/master/styles/syntax-variables.less#L45), so maybe the brackets are magenta.

**Comment by schmittyjd** [comment]
@benogle the blue tag names look similar to how HTML is currently colored

**Comment by benogle** [comment]
> @benogle the blue tag names look similar to how HTML is currently colored

Right, IMO, that's a good thing. I think we should remove the magenta from the closing tags for consistency.

**Comment by schmittyjd** [comment]
@benogle alright, here is how it looks now (exactly how html tags are colored)

**Comment by benogle** [comment]
:+1:

**Pull request merged**
