### PR TITLE
increase contrast for background color of selections

### PR DESCRIPTION
**Pull request by janwijbrand**
### Description of the Change

I really love the dark colorized syntax theme. There is however drawback in my opinion and that's too little contrast between the normal background color and that of selections. It makes it very hard to discern where selections start and stop, esp. when doing multi-cursor selections. 

### Alternate Designs

The current selection background color seems to be "dictated" by Solarized. Solarized does not provide alternatives. I see this as a shortcoming in Solarized.

### Benefits

Selected characters and lines stand out very very well.

### Possible Drawbacks

This change might divert from Solarized's concepts.

### CODE REVIEW

**Comment by janwijbrand** [comment]
Default selection background color, provides little contrast:

lowcontrast

Higher contrast selection backgrounds make them stand out much better:

highcontrast

**Comment by simurai** [comment]
> The current selection background color seems to be "dictated" by Solarized.

Yeah, I agree that the selection is a bit too low in contrast. But I still think this theme should stay as close to the [original](http://ethanschoonover.com/solarized) as possible:

screen shot 2017-02-02 at 12 09 54 pm

Have you thought about publishing a customized Solarized theme with this tweak? There are also other [Solarized variations](https://atom.io/themes/search?utf8=%E2%9C%93&q=solarized) available. Like `solarized-dark-bold-syntax` makes the selection color a bit [lighter](https://github.com/bassu/solarized-dark-bold-syntax/blob/53492da160a20937d83cbc40141046366e1c7c9c/styles/syntax-variables.less#L11).

**Comment by janwijbrand** [comment]
Thank you for your response!

In my opinion "practically beats purity" in these cases: the low contrast makes the selection's background color, esp. on less-than-ideal monitors, basically useless.

I understand the possibility of publishing yet another variation of the theme. I would love the core-theme to be more usable though. If the PR (with perhaps a tweaked value for the background color?) is not accepted, I'll see to publish a custom theme.

**Comment by simurai** [comment]
> PR (with perhaps a tweaked value for the background color?)

Yeah, I would say the inverted background color would be a too drastic change. But a [slightly lighter](https://github.com/bassu/solarized-dark-bold-syntax/blob/53492da160a20937d83cbc40141046366e1c7c9c/styles/syntax-variables.less#L11) color might be ok. 👍

**Comment by janwijbrand** [comment]
I've update the PR with your suggestion.

I found that I'm not the only one "complaining" about the low-contrast issue (see for example here: https://github.com/altercation/solarized/issues/239). Updating the Solarized core-theme for Atom seems to me a useful change.

Personally, I'll go with a custom theme that includes the 'drastic' inverted background color as usability increase as drastically with it :)

**Comment by simurai** [comment]
@janwijbrand Thanks. 🙇 

> Personally, I'll go with a custom theme that includes the 'drastic' inverted background color as usability increase as drastically with it :)

:smile:

**Comment by janwijbrand** [comment]
Thanks @simurai !

**Pull request merged**
