### PR TITLE
make selections more visible

### PR DESCRIPTION
**Pull request by gregplaysguitar**
Selection highlights were very difficult to see, this increases the contrast a little

### CODE REVIEW

**Comment by benogle** [comment]
Screenshot of before and after?

**Comment by gregplaysguitar** [comment]
Here you go: 

old
new

**Comment by benogle** [comment]
@schmittyjd what do you think?

**Comment by schmittyjd** [comment]
@benogle It seems to make selections a tad more prominent, I see no problem merging this

**Pull request merged**
