### PR TITLE
color function names in classes

### PR DESCRIPTION
**Pull request by joseramonc**
Add different color to function names in coffeescript classes
screen shot 2015-10-05 at 11 15 50 am
screen shot 2015-10-05 at 11 18 39 am

### CODE REVIEW

**Comment by izuzak** [comment]
cc @simurai for :eyes:

**Comment by simurai** [comment]
The change looks good.

Here the screenshots from https://github.com/atom/language-examples/blob/master/languages/coffeescript.coffee#L1-L25

Before:

screen shot 2015-10-13 at 12 31 50 pm

After:

screen shot 2015-10-13 at 12 32 12 pm

Maybe something to consider. `@green` also gets used for `.keyword`. Does that make sense to use it also for functions? Textmate seems to use `@blue`: https://tmtheme-editor.herokuapp.com/#!/editor/theme/Solarized%20(dark) /cc @schmittyjd

**Comment by joseramonc** [comment]
@simurai Is it ok if I update this pull request to match textmate solarized dark's coffeescript? I just didn't knew where to take reference for coffeescript because there's no official solarized dark :disappointed:. I updated the functions color because didn't seemed right to me

**Comment by simurai** [comment]
> Is it ok if I update this pull request to match textmate solarized dark's coffeescript?

Yeah, sounds good. I think originally, this theme got ported from textmate, so staying close to that should be fine.

**Comment by joseramonc** [comment]
I have updated the coffeescript syntax. For reference: 

Before: 

screen shot 2015-10-16 at 10 13 59 am


After:

screen shot 2015-10-16 at 10 12 59 am

**Comment by simurai** [comment]
Looks great. Thanks.

**Comment by schmittyjd** [comment]
@simurai be sure to bump the version/tag number too :+1:

**Comment by simurai** [comment]
@schmittyjd Yes, right. I'll merge #50 and publish a new release.

**Pull request merged**
