### PR TITLE
Match javascript syntax to solarized dark syntax

### PR DESCRIPTION
**Pull request by joseramonc**
Before:
screen shot 2015-02-03 at 4 16 04 pm

After:
screen shot 2015-02-03 at 4 15 29 pm

For reference, the ideal .js file: http://ethanschoonover.com/solarized/img/screen-javascript-dark.png

### CODE REVIEW

**Comment by schmitzjake** [comment]
Hmmmm. Looks nice, although I do prefer having more colors than just blue green and cyan. The way vim renders javascript files is lacking by default, a lot of people use 3rd party plugins to enhance the highlighting, that is what my original modifications to the javascript were based off of. This does look organized though.

**Comment by schmitzjake** [comment]
I will say that I thouroughly enjoy having parameters inside of function definitions being red

**Comment by joseramonc** [comment]
@schmitzjake shouldn't this repo be like the original solarized dark, and if more colors are required (your case) then install it as another plugin? is it possible to add configurations or something to this theme?

**Comment by schmitzjake** [comment]
Good point

**Comment by schmitzjake** [comment]
Could you squash those commits?

**Comment by 50Wliu** [comment]
@schmitzjake the Atom team doesn't require PR commits to be squashed-I believe it was @kevinsawicki who said that it's the journey that really counts.

**Comment by schmitzjake** [comment]
The journey it is then. Good work @joseramonc ! :+1:

**Pull request merged**
