### PR TITLE
Language variables

### PR DESCRIPTION
**Pull request by simurai**
This PR adds language variables used by Autocomplete plus https://github.com/atom-community/autocomplete-plus/issues/351

### CODE REVIEW

**Comment by schmittyjd** [comment]
I'm curious as to why this is needed in the syntax coloring. Shouldn't it be supported by a language package?

**Comment by benogle** [comment]
The idea is that packages can match colors with that of specific types of symbols. This will be used in autocomplete-plus to colorize type icons that match the syntax color.

So if functions are blue, an function suggested by autocomplete will show the same blue next to it.

**Comment by schmittyjd** [comment]
seems ok to me

**Comment by simurai** [comment]
Sometimes Syntax themes use different colors for different languages and not just the same for all. E.g. "variables" in language A has a different color than language B. So some tweaking might still needed.

Also I wasn't sure about `@syntax-color-snippet`. Will it be used for code snippets? In this theme it's just mapped to `@syntax-color-keyword`.

**Comment by schmittyjd** [comment]
Pretty swamped at the moment. I'll check it out come this weekend

**Comment by simurai** [comment]
@schmittyjd No, problem. Actually there isn't anything to do right now. Was just an "aside note" that it's a first pass and once we start using it in Autocomplete plus, we might discover that things can be improved.

**Pull request merged**
