### PR TITLE
Added Javascript interpolated template string syntax coloring

### PR DESCRIPTION
**Pull request by cbankester**
* Color template string interpolation punctuation red
* Unset string color for contents of template string interpolation

### CODE REVIEW

**Comment by schmittyjd** [comment]
Could you show some before and after screenshots?

**Comment by cbankester** [comment]
Before:
screen shot 2015-08-14 at 5 50 56 pm

After:
screen shot 2015-08-14 at 5 51 51 pm

**Comment by cbankester** [comment]
Looks like I made a mistake with the selector: 
screen shot 2015-08-14 at 5 55 19 pm
(the ending semicolon and function-body closing bracket are red).

I'll fix that as soon as I can.

**Comment by schmittyjd** [comment]
@cbankester alright. Looks good! Once you fix this ping me and we will get this pulled in :+1:

**Comment by cbankester** [comment]
I fixed the selector issue, but uncovered a bug in [atom/language-javascript](https://github.com/atom/language-javascript) that causes the closing bracket of a non-empty function body inside template string interpolation to be marked-up as the closing bracket of the interpolation. See, e.g.:
screen shot 2015-08-15 at 10 35 48 pm

I'll be opening an issue or pull request on that package soon, but as far as I'm aware, the styles here are correct now.

**Comment by schmittyjd** [comment]
Nice work @cbankester I will say that I would probably prefer for the language-javascript issue to be resolved first though

**Comment by cbankester** [comment]
Agreed. I poked around their source, but it's quite convoluted. I'll keep y'all updated on if a fix lands.

Christian Bankester
cbankester@immense.net<mailto:cbankester@immense.net>




On Mon, Aug 17, 2015 at 11:12 AM -0700, "Jake Schmitz" <notifications@github.com<mailto:notifications@github.com>> wrote:


Nice work @cbankester<https://github.com/cbankester> I will say that I would probably prefer for the language-javascript issue to be resolved first though

-

**Comment by schmittyjd** [comment]
Awesome. Looking forward to getting this pulled in!

**Comment by schmittyjd** [comment]
@cbankester I have filed an issue on the atom/language-javascript repo. 
<a href="https://github.com/atom/language-javascript/issues/199">atom/language-javascript#199</a>

**Comment by schmittyjd** [comment]
@cbankester atom/language-javascript#199 has been resolved. I will take care of merging this in now! :+1:

**Comment by MayhemYDG** [comment]
@schmittyjd @cmbankester 
Looks like it regressed at some point.
image

**Pull request merged**
